# Generated by Django 3.2.2 on 2021-07-31 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('marvel_id', models.PositiveBigIntegerField(default=1, unique=True, verbose_name='marvel_ids')),
            ],
            options={
                'db_table': 'e_commerce_comics',
            },
        ),
    ]
