# Generated by Django 3.2.2 on 2021-07-31 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='description',
            field=models.TextField(default='', verbose_name='descriptions'),
        ),
        migrations.AddField(
            model_name='comic',
            name='picture',
            field=models.URLField(default='', verbose_name='pictures'),
        ),
        migrations.AddField(
            model_name='comic',
            name='price',
            field=models.FloatField(default=0.0, max_length=5, verbose_name='prices'),
        ),
        migrations.AddField(
            model_name='comic',
            name='stock_qty',
            field=models.PositiveIntegerField(default=0, verbose_name='stock_qty'),
        ),
        migrations.AddField(
            model_name='comic',
            name='title',
            field=models.TextField(default='', max_length=120, verbose_name='titles'),
        ),
    ]
