# Generated by Django 3.2.2 on 2021-08-03 00:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('e_commerce', '0002_auto_20210731_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('favorite', models.BooleanField(default=None, verbose_name='favorites')),
                ('cart', models.BooleanField(default=None, verbose_name='shopping_cart')),
                ('wished_qty', models.PositiveIntegerField(default=0, verbose_name='wished_qty')),
                ('buied_qty', models.PositiveIntegerField(default=0, verbose_name='buied_qty')),
                ('comid_id', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='e_commerce.comic', verbose_name='Comic')),
                ('user_id', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'db_table': 'e_commerce_wish_list',
            },
        ),
    ]
