# Generated by Django 3.2.2 on 2021-08-03 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0004_auto_20210803_2215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='comid',
            new_name='comic',
        ),
    ]
